server:
  port: 8080
spring:
  application:
    name: gateway-liu
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
#      - id: route_one
#        uri: http://192.168.143.222:8089
#        predicates:
#        - Path=/test/**
#      - id: route_two
#        uri: http://192.168.143.222:8089
#        predicates:
#        - Header=KEY, 123
#      - id: route_three
#        uri: lb://DEMO
#        filters:
#        - AddRequestParameter=foo, bar
#        predicates:
#        - Method=GET
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8889/eureka
logging:
  level:
    org.springframework.cloud.gateway: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"